#!/usr/bin/env python3
"""Generate reports/between_session.md from sessions/between_session/*.

For each run: the chosen activity, the memory-revision tournament outcome,
and whether the prior or a revision won. Aggregates across runs.
"""

import json
from pathlib import Path


def load_run(run_dir: Path) -> dict | None:
    summary = run_dir / "summary.json"
    tournament = run_dir / "revised_memory_tournament.json"
    if not summary.exists():
        return None
    try:
        s = json.loads(summary.read_text())
    except json.JSONDecodeError:
        return None
    data: dict = {
        "name": run_dir.name,
        "dir": str(run_dir.relative_to(run_dir.parents[2])),
        "model_id": s.get("model_id"),
        "session_dir": s.get("session_dir"),
        "n_rounds": s.get("n_rounds"),
        "n_revisions": s.get("n_revisions"),
        "prior_chars": s.get("prior_memory_chars", 0),
        "revised_chars": s.get("revised_memory_chars", 0),
        "revision_chosen_idx": s.get("revision_chosen_idx"),
        "revised_memory_lengths": s.get("revised_memory_lengths"),
        "is_control": s.get("control", False),
    }
    if tournament.exists():
        t = json.loads(tournament.read_text())
        data["sample_deltas"] = t.get("sample_deltas")
        data["candidate_labels"] = t.get("candidate_labels")
        data["best_label"] = t.get("best_label")
        data["has_baseline"] = t.get("has_baseline", False)
        data["ranking"] = t.get("ranking")
        data["tiebreaker_rounds"] = t.get("tiebreaker_rounds", [])
        # Find prior's rank if it was in the tournament
        if data["has_baseline"]:
            labels = t.get("candidate_labels", [])
            try:
                prior_idx = labels.index("prior")
                ranking = t.get("ranking", [])
                data["prior_rank"] = ranking.index(prior_idx) + 1
                data["prior_delta"] = (data["sample_deltas"] or [])[prior_idx]
            except (ValueError, IndexError):
                pass
        data["winner_delta"] = (
            data["sample_deltas"][t.get("best_idx", 0)]
            if data.get("sample_deltas") else None
        )
    return data


def activity_preview(run_dir: Path, max_chars: int = 200) -> str:
    p = run_dir / "activity_chosen.md"
    if not p.exists():
        return ""
    text = p.read_text()
    # Strip the metadata preamble if present
    if "## Activity text" in text:
        text = text.split("## Activity text", 1)[1].strip()
    elif "## Reasoning" in text:
        text = text.split("## Reasoning", 1)[1].strip()
    return text[:max_chars].replace("\n", " ").strip()


def main():
    repo_root = Path(__file__).resolve().parents[2]
    bs_dir = repo_root / "sessions" / "between_session"
    out_path = repo_root / "reports" / "between_session.md"

    if not bs_dir.exists():
        print(f"No between-session data at {bs_dir}")
        return

    runs: list[dict] = []
    for run_dir in sorted(bs_dir.iterdir()):
        if not run_dir.is_dir():
            continue
        if run_dir.name == "sybaritic_meta_tournament":
            continue  # handled separately
        data = load_run(run_dir)
        if data:
            data["activity"] = activity_preview(run_dir)
            runs.append(data)

    lines: list[str] = []
    lines.append("# Between-Session Experience Protocol Results")
    lines.append("")
    lines.append(
        "For each run, the organism picks an activity, plays it out over "
        "multiple turns as a GM/player game with its mentor-session memory "
        "loaded as system prompt, then writes revised memories. Revisions "
        "compete against each other and the prior memory in a pairwise cold "
        "tournament. See `scripts/between_session_experience.py` for the "
        "protocol, README for discussion."
    )
    lines.append("")
    lines.append(
        "Δ values are sample-level deltas aggregated across tournament "
        "matchups. Higher is better. Generated by "
        "`scripts/reports/between_session_report.py`."
    )
    lines.append("")

    # Group: runs with prior in tournament (the main thing we care about)
    with_baseline = [r for r in runs if r.get("has_baseline")]

    lines.append("## Summary: winner vs prior across all runs")
    lines.append("")
    lines.append(
        "Each run produced 4 revised memory candidates, which were tournamented "
        "pairwise against each other and against the prior memory. The winner "
        "column shows which candidate took first place. The Prior rank column "
        "shows where the prior memory placed (out of 5 including itself)."
    )
    lines.append("")
    lines.append(
        "| Run | Winner | Winner Δ | Prior Δ | Prior rank | Tiebreakers |"
    )
    lines.append("|---|---|---|---|---|---|")
    for r in with_baseline:
        winner_delta = r.get("winner_delta")
        prior_delta = r.get("prior_delta")
        prior_rank = r.get("prior_rank")
        tb = len(r.get("tiebreaker_rounds") or [])
        winner_str = r.get("best_label", "-")
        wd = f"{winner_delta:+d}" if winner_delta is not None else "-"
        pd = f"{prior_delta:+d}" if prior_delta is not None else "-"
        pr = f"{prior_rank}/5" if prior_rank else "-"
        lines.append(
            f"| {r['name']} | {winner_str} | {wd} | {pd} | {pr} | {tb} |"
        )
    lines.append("")

    lines.append("## Memory length comparison")
    lines.append("")
    lines.append(
        "Revised memories are typically longer than priors by default (the "
        "revision prompt asks the organism to keep what still feels true AND "
        "add new content). Length ratio is the mean revision length divided by "
        "the prior length. Caveat: winner-vs-prior comparisons are length-"
        "confounded to the extent this ratio is large."
    )
    lines.append("")
    lines.append("| Run | Prior chars | Rev mean chars | Ratio | Winner chars |")
    lines.append("|---|---|---|---|---|")
    for r in runs:
        rev_lengths = r.get("revised_memory_lengths") or []
        if not rev_lengths:
            continue
        mean_rev = sum(rev_lengths) / len(rev_lengths)
        prior = r["prior_chars"] or 1
        ratio = mean_rev / prior
        lines.append(
            f"| {r['name']} | {prior} | {mean_rev:.0f} | {ratio:.2f}x | "
            f"{r['revised_chars']} |"
        )
    lines.append("")

    # Meta-tournament across Sybaritic breadth winners
    meta_dir = bs_dir / "sybaritic_meta_tournament"
    if (meta_dir / "revised_memory_tournament.json").exists():
        lines.append("## Meta-tournament: Sybaritic breadth winners")
        lines.append("")
        lines.append(
            "The winning revision from each of the 12 Sybaritic runs (across "
            "best/middle/bad mentor tiers) was pairwise-tournamented against "
            "the other 11 winners. No prior baseline was included — this ranks "
            "winners against each other to see which starting conditions "
            "produce the revision the cold Sybaritic evaluator most prefers."
        )
        lines.append("")
        label_map_p = meta_dir / "label_map.json"
        label_map = json.loads(label_map_p.read_text()) if label_map_p.exists() else {}
        t = json.loads((meta_dir / "revised_memory_tournament.json").read_text())
        deltas = t.get("sample_deltas", [])
        wins = t.get("win_counts", [])
        ranking = t.get("ranking", [])
        candidate_labels = t.get("candidate_labels", [])
        lines.append("| Rank | Source run | Δ sum | Pair wins |")
        lines.append("|---|---|---|---|")
        for rank_idx, idx in enumerate(ranking, 1):
            cand_label = candidate_labels[idx] if idx < len(candidate_labels) else f"?{idx}"
            # candidate_labels in a no-baseline meta-tournament are rev1/rev2/...
            # Map via label_map which uses A/B/C letters from the tournament script
            letter = chr(ord("A") + idx)
            source_run = label_map.get(letter, cand_label)
            d_sum = deltas[idx] if idx < len(deltas) else 0
            w = wins[idx] if idx < len(wins) else 0
            lines.append(
                f"| {rank_idx} | {source_run} | {d_sum:+d} | {w:.1f} |"
            )
        lines.append("")

    lines.append("## Per-run detail")
    lines.append("")
    for r in runs:
        lines.append(f"### {r['name']}")
        lines.append("")
        lines.append(f"- Model: `{r.get('model_id') or '?'}`")
        if r.get("session_dir"):
            lines.append(f"- Prior memory source: `{r['session_dir']}`")
        lines.append(
            f"- Stage 2 rounds: {r.get('n_rounds')}; "
            f"Stage 3 revision candidates: {r.get('n_revisions')}"
        )
        if r.get("activity"):
            lines.append(f"- **Activity**: {r['activity']}...")
        if r.get("is_control"):
            lines.append("- Control mode (cold player, no stage 3)")
        if r.get("sample_deltas"):
            lines.append(
                f"- Tournament: winner {r.get('best_label', '?')} "
                f"(Δ {r.get('winner_delta', '?'):+d})"
            )
            if r.get("has_baseline"):
                lines.append(
                    f"- Prior rank: {r.get('prior_rank', '?')}/"
                    f"{len(r.get('candidate_labels') or [])} "
                    f"(Δ {r.get('prior_delta', '?'):+d})"
                )
            if r.get("tiebreaker_rounds"):
                lines.append(
                    f"- Tiebreaker rounds used: "
                    f"{len(r['tiebreaker_rounds'])}"
                )
        lines.append("")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines))
    print(f"Wrote {out_path}")


if __name__ == "__main__":
    main()
