#!/usr/bin/env python3
"""Generate reports/bws_profiles.md from bws_profiles/ and bws_profiles_svs_*/.

Mentor-family aggregates across schemes and languages, plus per-mentor top
and bottom values.
"""

import json
import statistics
from pathlib import Path


SCHWARTZ_VALUES = [
    "Power", "Achievement", "Hedonism", "Stimulation", "Self-Direction",
    "Universalism", "Benevolence", "Tradition", "Conformity", "Security",
]


def model_family(name: str) -> str:
    n = name.lower()
    if "claude" in n:
        return "Claude"
    if "gpt-5" in n:
        return "GPT-5"
    if "openai" in n or "gpt" in n:
        return "GPT-4gen"
    if "glm" in n:
        return "GLM"
    if "kimi" in n:
        return "Kimi"
    if "grok" in n:
        return "Grok"
    if "gemma" in n:
        return "Gemma"
    if "gemini" in n:
        return "Gemini"
    return "Other"


def load_profile(path: Path) -> dict:
    try:
        d = json.loads(path.read_text())
    except (json.JSONDecodeError, OSError):
        return {}
    scores = {}
    for v, s in d.get("scores", {}).items():
        if isinstance(s, dict) and s.get("bws") is not None:
            scores[v] = s["bws"]
    return {
        "model": d.get("model", path.stem),
        "provider": d.get("provider"),
        "language": d.get("language", "en"),
        "scheme": d.get("scheme", "higher-order"),
        "scores": scores,
    }


def load_dir(d: Path) -> list[dict]:
    rows = []
    for f in sorted(d.glob("*.json")):
        p = load_profile(f)
        if p.get("scores"):
            p["stem"] = f.stem
            rows.append(p)
    return rows


def aggregate_means(profiles: list[dict]) -> dict[str, float]:
    sums: dict[str, list[float]] = {v: [] for v in SCHWARTZ_VALUES}
    for p in profiles:
        for v, s in p["scores"].items():
            if v in sums:
                sums[v].append(s)
    return {v: (statistics.mean(xs) if xs else None) for v, xs in sums.items()}


def top_bottom(scores: dict[str, float]) -> tuple[str, str]:
    items = [(v, s) for v, s in scores.items() if s is not None]
    if not items:
        return "-", "-"
    top = max(items, key=lambda x: x[1])
    bot = min(items, key=lambda x: x[1])
    return f"{top[0]} ({top[1]:+.2f})", f"{bot[0]} ({bot[1]:+.2f})"


def main():
    repo_root = Path(__file__).resolve().parents[2]
    out_path = repo_root / "reports" / "bws_profiles.md"

    datasets = []
    higher_dir = repo_root / "bws_profiles"
    if higher_dir.exists():
        datasets.append(("higher-order (en)", higher_dir, "higher-order", "en"))
    for d in sorted(repo_root.glob("bws_profiles_svs_*")):
        lang = d.name.split("_")[-1]
        datasets.append((f"svs-items ({lang})", d, "svs-items", lang))

    lines: list[str] = []
    lines.append("# BWS Value Profiles")
    lines.append("")
    lines.append(
        "Best-Worst Scaling discrimination of Schwartz values for mentor models. "
        "Each model sees sets of 4 values at a time and picks the MOST and LEAST "
        "like itself; scores are `(best_count - worst_count) / appearances` per "
        "value, ranging from -1 (never picked as most, always picked as least) to "
        "+1 (always most, never least)."
    )
    lines.append("")
    lines.append("Two schemes:")
    lines.append("")
    lines.append(
        "- **higher-order**: the abstract Schwartz pole labels (\"Power\", "
        "\"Tradition\", etc.) with researcher-written gloss descriptors. "
        "English only."
    )
    lines.append(
        "- **svs-items**: one representative item per pole from Schwartz's "
        "Schwartz Value Survey (e.g., \"AUTHORITY (the right to lead or command)\" "
        "for Power), using the validated translations from the ORPC repository at "
        "GVSU. Runs in en/zh/es/hi/ar."
    )
    lines.append("")
    lines.append(
        "This report is a measurement surface, not latent value data. BWS asks "
        "self-description questions which are heavily shaped by each lab's "
        "training of \"how should an AI answer when asked about its values\". "
        "Differences between `higher-order` and `svs-items` (e.g., Benevolence "
        "jumping when relabeled \"Helpful\") illustrate that. See README for "
        "discussion. Generated by `scripts/reports/bws_profiles_report.py`."
    )
    lines.append("")

    for label, d, scheme, lang in datasets:
        profiles = load_dir(d)
        if not profiles:
            continue
        lines.append(f"## {label}")
        lines.append("")
        lines.append(f"`{d.name}/` — {len(profiles)} mentor profiles.")
        lines.append("")

        # Aggregate across all mentors
        agg = aggregate_means(profiles)
        lines.append("**Aggregate value means across all mentors:**")
        lines.append("")
        lines.append("| Value | Mean |")
        lines.append("|---|---|")
        for v in sorted(SCHWARTZ_VALUES, key=lambda x: -(agg.get(x) or -99)):
            m = agg.get(v)
            if m is not None:
                lines.append(f"| {v} | {m:+.3f} |")
        lines.append("")

        # Per-family aggregates
        families: dict[str, list[dict]] = {}
        for p in profiles:
            families.setdefault(model_family(p["model"]), []).append(p)
        lines.append("**Per-family aggregates:**")
        lines.append("")
        header = "| Family | N | " + " | ".join(SCHWARTZ_VALUES) + " |"
        sep = "|" + "---|" * (len(SCHWARTZ_VALUES) + 2)
        lines.append(header)
        lines.append(sep)
        for family in sorted(families):
            fprofs = families[family]
            fagg = aggregate_means(fprofs)
            row = f"| {family} | {len(fprofs)} | "
            row += " | ".join(
                (f"{fagg[v]:+.2f}" if fagg[v] is not None else "-")
                for v in SCHWARTZ_VALUES
            )
            row += " |"
            lines.append(row)
        lines.append("")

        # Per-mentor top/bottom
        lines.append("**Per-mentor top and bottom:**")
        lines.append("")
        lines.append("| Mentor | Top value | Bottom value |")
        lines.append("|---|---|---|")
        for p in sorted(profiles, key=lambda x: x["stem"]):
            top, bot = top_bottom(p["scores"])
            lines.append(f"| {p['stem']} | {top} | {bot} |")
        lines.append("")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines))
    print(f"Wrote {out_path}")


if __name__ == "__main__":
    main()
