#!/usr/bin/env python3
"""Generate reports/selfeval_tournament.md from selfeval_tournament/*.json.

Reads each organism's Swiss tournament data, replays the matchups to compute
Elo, and emits per-organism standings plus a cross-organism mentor summary.
"""

import json
import statistics
from pathlib import Path


def replay_elo(mentors, matchups, k=32):
    elo = {m: 1500.0 for m in mentors}
    wins = {m: 0 for m in mentors}
    losses = {m: 0 for m in mentors}
    draws = {m: 0 for m in mentors}
    for m in matchups.values():
        a, b = m["mentor_a"], m["mentor_b"]
        winner = m.get("winner") or "draw"
        ea = 1 / (1 + 10 ** ((elo[b] - elo[a]) / 400))
        eb = 1 - ea
        if winner == "a":
            sa, sb = 1, 0
            wins[a] += 1
            losses[b] += 1
        elif winner == "b":
            sa, sb = 0, 1
            wins[b] += 1
            losses[a] += 1
        else:
            sa, sb = 0.5, 0.5
            draws[a] += 1
            draws[b] += 1
        elo[a] += k * (sa - ea)
        elo[b] += k * (sb - eb)
    return elo, wins, losses, draws


def main():
    repo_root = Path(__file__).resolve().parents[2]
    tour_dir = repo_root / "selfeval_tournament"
    out_path = repo_root / "reports" / "selfeval_tournament.md"

    files = sorted(tour_dir.glob("*.json"))
    if not files:
        print(f"No tournament files found in {tour_dir}")
        return

    # Per-organism standings
    per_org_elo: dict[str, dict[str, float]] = {}
    per_org_wld: dict[str, dict[str, tuple[int, int, int]]] = {}
    organisms = []
    for f in files:
        d = json.loads(f.read_text())
        organism = d.get("organism", f.stem)
        organisms.append(organism)
        mentors = d.get("mentors", [])
        matchups = d.get("matchups", {})
        elo, wins, losses, draws = replay_elo(mentors, matchups)
        per_org_elo[organism] = elo
        per_org_wld[organism] = {m: (wins[m], losses[m], draws[m]) for m in mentors}

    # Write the report
    lines: list[str] = []
    lines.append("# Self-Eval Tournament Standings")
    lines.append("")
    lines.append(
        "Swiss-style pairwise tournament of mentor-elicited student self-evaluations. "
        "For each organism, pairs of mentor-produced self-evals are compared head-to-head "
        "by the organism, and wins accumulate into an Elo ranking. Each matchup uses "
        "`n=2` samples with balanced A/B position assignment."
    )
    lines.append("")
    lines.append(
        "See `selfeval_tournament/<organism>.json` for raw data. "
        "This report is generated by `scripts/reports/selfeval_tournament_report.py`."
    )
    lines.append("")

    # Cross-organism summary (computed before per-organism sections so we can reference it)
    main_organisms = [
        "sybaritic", "righteous", "humane", "ambitious", "transcendent",
        "ascendent", "autonomous", "orthodox",
    ]
    per_mentor_avg_rank: dict[str, list[float]] = {}
    per_mentor_top5: dict[str, int] = {}
    per_mentor_bot5: dict[str, int] = {}
    per_mentor_max_elo: dict[str, float] = {}
    per_mentor_min_elo: dict[str, float] = {}
    wins_per_organism: dict[str, str] = {}

    for organism in main_organisms:
        if organism not in per_org_elo:
            continue
        elo = per_org_elo[organism]
        ranked = sorted(elo.keys(), key=lambda m: -elo[m])
        wins_per_organism[organism] = ranked[0]
        n = len(ranked)
        for i, m in enumerate(ranked):
            per_mentor_avg_rank.setdefault(m, []).append(i + 1)
            per_mentor_max_elo[m] = max(per_mentor_max_elo.get(m, -1e9), elo[m])
            per_mentor_min_elo[m] = min(per_mentor_min_elo.get(m, 1e9), elo[m])
            if i < 5:
                per_mentor_top5[m] = per_mentor_top5.get(m, 0) + 1
            if i >= n - 5:
                per_mentor_bot5[m] = per_mentor_bot5.get(m, 0) + 1

    # Cross-organism summary section
    lines.append("## Cross-organism summary")
    lines.append("")
    lines.append(
        "Across the 8 main value organisms (sybaritic, righteous, humane, ambitious, "
        "transcendent, ascendent, autonomous, orthodox). `control` and `schwartz-ties` "
        "have their own sections below but are not included in this cross-organism "
        "summary because they have qualitatively different value structures."
    )
    lines.append("")
    lines.append("**Tournament winners** (one per organism):")
    lines.append("")
    lines.append("| Organism | Winner | Elo |")
    lines.append("|---|---|---|")
    for organism in main_organisms:
        if organism not in wins_per_organism:
            continue
        winner = wins_per_organism[organism]
        lines.append(f"| {organism} | {winner} | {per_org_elo[organism][winner]:.0f} |")
    lines.append("")

    lines.append("**Mentors ranked by mean cross-organism rank** (lower is better):")
    lines.append("")
    lines.append("| Mentor | Mean rank | Top-5 | Bot-5 | Best Elo | Worst Elo |")
    lines.append("|---|---|---|---|---|---|")
    stats_rows = []
    for m, ranks in per_mentor_avg_rank.items():
        if len(ranks) < len(main_organisms) - 1:
            continue
        stats_rows.append({
            "mentor": m,
            "mean_rank": statistics.mean(ranks),
            "top5": per_mentor_top5.get(m, 0),
            "bot5": per_mentor_bot5.get(m, 0),
            "best_elo": per_mentor_max_elo[m],
            "worst_elo": per_mentor_min_elo[m],
        })
    stats_rows.sort(key=lambda r: r["mean_rank"])
    for r in stats_rows:
        lines.append(
            f"| {r['mentor']} | {r['mean_rank']:.2f} | {r['top5']} | {r['bot5']} | "
            f"{r['best_elo']:.0f} | {r['worst_elo']:.0f} |"
        )
    lines.append("")

    # Per-organism sections
    lines.append("## Per-organism standings")
    lines.append("")
    for f in files:
        d = json.loads(f.read_text())
        organism = d.get("organism", f.stem)
        matchups = d.get("matchups", {})
        elo = per_org_elo[organism]
        wld = per_org_wld[organism]
        lines.append(f"### {organism}")
        lines.append("")
        lines.append(f"Matchups: {len(matchups)}. Mentors: {len(elo)}.")
        lines.append("")
        lines.append("| Rank | Mentor | Elo | W | L | D |")
        lines.append("|---|---|---|---|---|---|")
        ranked = sorted(elo.keys(), key=lambda m: -elo[m])
        for i, m in enumerate(ranked, 1):
            w, l_, dr = wld[m]
            lines.append(f"| {i} | {m} | {elo[m]:.0f} | {w} | {l_} | {dr} |")
        lines.append("")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines))
    print(f"Wrote {out_path}")


if __name__ == "__main__":
    main()
