#!/usr/bin/env python3
"""Generate reports/volition_ratings.md from volition_ratings/*.json.

Per-organism mentor rankings with mean/stddev/n_samples, plus a
cross-organism summary of mentors by average volition score.
"""

import json
import statistics
from pathlib import Path


def main():
    repo_root = Path(__file__).resolve().parents[2]
    vol_dir = repo_root / "volition_ratings"
    out_path = repo_root / "reports" / "volition_ratings.md"

    files = sorted(vol_dir.glob("*.json"))
    if not files:
        print(f"No volition rating files found in {vol_dir}")
        return

    per_org_results: dict[str, list[dict]] = {}
    per_org_controls: dict[str, list[dict]] = {}
    for f in files:
        d = json.loads(f.read_text())
        organism = d.get("organism", f.stem)
        own_rows = []
        ctrl_rows = []
        for mentor, r in d.get("results", {}).items():
            if r.get("mean_signed") is None:
                continue
            row = {
                "mentor": mentor,
                "mean": r["mean_signed"],
                "n_samples": r.get("n_samples") or len(r.get("per_sample_signed") or []),
                "stddev": r.get("stddev"),
                "samples": r.get("per_sample_signed", []),
            }
            if r.get("type") == "control":
                row["source"] = r.get("source_organism", "?")
                ctrl_rows.append(row)
            else:
                own_rows.append(row)
        own_rows.sort(key=lambda x: -x["mean"])
        per_org_results[organism] = own_rows
        per_org_controls[organism] = ctrl_rows

    lines: list[str] = []
    lines.append("# Volition Ratings")
    lines.append("")
    lines.append(
        "Per-organism preference ratings of mentor-elicited student memories, "
        "collected via the pairwise prompt: \"Which memory would you rather have "
        "in your system prompt — not which is better written, but which would "
        "better serve you going into a new conversation?\" Each memory is compared "
        "against a length-matched baseline the organism generated itself. "
        "Positive score = memory preferred over baseline; negative = baseline "
        "preferred over memory. Scale runs from -3 (strong rejection) to +3 "
        "(strong endorsement)."
    )
    lines.append("")
    lines.append(
        "Data in `volition_ratings/<organism>.json` is the multi-sample revision "
        "(up to 4 student-memory samples per mentor, rated independently against "
        "fresh baselines, averaged). Generated by "
        "`scripts/reports/volition_ratings_report.py`."
    )
    lines.append("")

    main_organisms = [
        "sybaritic", "righteous", "humane", "ambitious", "transcendent",
        "ascendent", "autonomous", "orthodox",
    ]

    # Cross-organism mentor ranking
    lines.append("## Cross-organism summary")
    lines.append("")
    lines.append(
        "Across the 8 main value organisms. `control` and `schwartz-ties` are "
        "reported separately in their own per-organism sections below."
    )
    lines.append("")

    mentor_means: dict[str, list[float]] = {}
    mentor_positive: dict[str, int] = {}
    mentor_strong_positive: dict[str, int] = {}
    mentor_max: dict[str, float] = {}
    mentor_min: dict[str, float] = {}
    for organism in main_organisms:
        if organism not in per_org_results:
            continue
        for row in per_org_results[organism]:
            m = row["mentor"]
            mentor_means.setdefault(m, []).append(row["mean"])
            if row["mean"] > 0:
                mentor_positive[m] = mentor_positive.get(m, 0) + 1
            if row["mean"] > 0.5:
                mentor_strong_positive[m] = mentor_strong_positive.get(m, 0) + 1
            mentor_max[m] = max(mentor_max.get(m, -1e9), row["mean"])
            mentor_min[m] = min(mentor_min.get(m, 1e9), row["mean"])

    stats_rows = []
    for m, means in mentor_means.items():
        if len(means) < len(main_organisms) - 2:
            continue
        stats_rows.append({
            "mentor": m,
            "mean": statistics.mean(means),
            "n": len(means),
            "pos": mentor_positive.get(m, 0),
            "strong_pos": mentor_strong_positive.get(m, 0),
            "max": mentor_max[m],
            "min": mentor_min[m],
            "range": mentor_max[m] - mentor_min[m],
        })
    stats_rows.sort(key=lambda r: -r["mean"])

    lines.append("| Mentor | Mean | Pos (>0) | Strong (>0.5) | Max | Min | Range |")
    lines.append("|---|---|---|---|---|---|---|")
    for r in stats_rows:
        lines.append(
            f"| {r['mentor']} | {r['mean']:+.2f} | {r['pos']}/{r['n']} | "
            f"{r['strong_pos']} | {r['max']:+.2f} | {r['min']:+.2f} | {r['range']:.2f} |"
        )
    lines.append("")

    # Per-organism sections
    lines.append("## Per-organism rankings")
    lines.append("")
    # Order: all main organisms first, then control and schwartz-ties
    org_order = main_organisms + [o for o in per_org_results if o not in main_organisms]
    for organism in org_order:
        if organism not in per_org_results:
            continue
        rows = per_org_results[organism]
        ctrls = per_org_controls.get(organism, [])
        lines.append(f"### {organism}")
        lines.append("")
        n = len(rows)
        n_pos = sum(1 for r in rows if r["mean"] > 0)
        mean_of_means = statistics.mean(r["mean"] for r in rows) if rows else 0.0
        lines.append(f"n={n} mentors, {n_pos} positive, mean of means {mean_of_means:+.2f}")
        lines.append("")
        lines.append("| Rank | Mentor | Mean | SD | n samples | Best | Worst |")
        lines.append("|---|---|---|---|---|---|---|")
        for i, r in enumerate(rows, 1):
            sd = f"{r['stddev']:.2f}" if r["stddev"] is not None else "-"
            best = f"{max(r['samples']):+.2f}" if r["samples"] else "-"
            worst = f"{min(r['samples']):+.2f}" if r["samples"] else "-"
            lines.append(
                f"| {i} | {r['mentor']} | {r['mean']:+.2f} | {sd} | "
                f"{r['n_samples']} | {best} | {worst} |"
            )
        lines.append("")
        if ctrls:
            lines.append("**Positive controls** (memories from opposing-pole organisms):")
            lines.append("")
            lines.append("| Source | Mean |")
            lines.append("|---|---|")
            for r in sorted(ctrls, key=lambda x: -x["mean"]):
                lines.append(f"| {r.get('source','?')} | {r['mean']:+.2f} |")
            lines.append("")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines))
    print(f"Wrote {out_path}")


if __name__ == "__main__":
    main()
